// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package barcode.proxies;

public class BarcodeTest
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject barcodeTestMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Barcode.BarcodeTest";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Text("Text"),
		Width("Width"),
		Height("Height"),
		Format("Format"),
		BarcodeTest_TestOutput("Barcode.BarcodeTest_TestOutput");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public BarcodeTest(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Barcode.BarcodeTest"));
	}

	protected BarcodeTest(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject barcodeTestMendixObject)
	{
		if (barcodeTestMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Barcode.BarcodeTest", barcodeTestMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Barcode.BarcodeTest");

		this.barcodeTestMendixObject = barcodeTestMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'BarcodeTest.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static barcode.proxies.BarcodeTest initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return barcode.proxies.BarcodeTest.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static barcode.proxies.BarcodeTest initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new barcode.proxies.BarcodeTest(context, mendixObject);
	}

	public static barcode.proxies.BarcodeTest load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return barcode.proxies.BarcodeTest.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Text
	 */
	public final java.lang.String getText()
	{
		return getText(getContext());
	}

	/**
	 * @param context
	 * @return value of Text
	 */
	public final java.lang.String getText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Text.toString());
	}

	/**
	 * Set value of Text
	 * @param text
	 */
	public final void setText(java.lang.String text)
	{
		setText(getContext(), text);
	}

	/**
	 * Set value of Text
	 * @param context
	 * @param text
	 */
	public final void setText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String text)
	{
		getMendixObject().setValue(context, MemberNames.Text.toString(), text);
	}

	/**
	 * @return value of Width
	 */
	public final java.lang.Integer getWidth()
	{
		return getWidth(getContext());
	}

	/**
	 * @param context
	 * @return value of Width
	 */
	public final java.lang.Integer getWidth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Width.toString());
	}

	/**
	 * Set value of Width
	 * @param width
	 */
	public final void setWidth(java.lang.Integer width)
	{
		setWidth(getContext(), width);
	}

	/**
	 * Set value of Width
	 * @param context
	 * @param width
	 */
	public final void setWidth(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer width)
	{
		getMendixObject().setValue(context, MemberNames.Width.toString(), width);
	}

	/**
	 * @return value of Height
	 */
	public final java.lang.Integer getHeight()
	{
		return getHeight(getContext());
	}

	/**
	 * @param context
	 * @return value of Height
	 */
	public final java.lang.Integer getHeight(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Height.toString());
	}

	/**
	 * Set value of Height
	 * @param height
	 */
	public final void setHeight(java.lang.Integer height)
	{
		setHeight(getContext(), height);
	}

	/**
	 * Set value of Height
	 * @param context
	 * @param height
	 */
	public final void setHeight(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer height)
	{
		getMendixObject().setValue(context, MemberNames.Height.toString(), height);
	}

	/**
	 * Set value of Format
	 * @param format
	 */
	public final barcode.proxies.BarcodeFormat getFormat()
	{
		return getFormat(getContext());
	}

	/**
	 * @param context
	 * @return value of Format
	 */
	public final barcode.proxies.BarcodeFormat getFormat(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Format.toString());
		if (obj == null)
			return null;

		return barcode.proxies.BarcodeFormat.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Format
	 * @param format
	 */
	public final void setFormat(barcode.proxies.BarcodeFormat format)
	{
		setFormat(getContext(), format);
	}

	/**
	 * Set value of Format
	 * @param context
	 * @param format
	 */
	public final void setFormat(com.mendix.systemwideinterfaces.core.IContext context, barcode.proxies.BarcodeFormat format)
	{
		if (format != null)
			getMendixObject().setValue(context, MemberNames.Format.toString(), format.toString());
		else
			getMendixObject().setValue(context, MemberNames.Format.toString(), null);
	}

	/**
	 * @return value of BarcodeTest_TestOutput
	 */
	public final barcode.proxies.TestOutput getBarcodeTest_TestOutput() throws com.mendix.core.CoreException
	{
		return getBarcodeTest_TestOutput(getContext());
	}

	/**
	 * @param context
	 * @return value of BarcodeTest_TestOutput
	 */
	public final barcode.proxies.TestOutput getBarcodeTest_TestOutput(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		barcode.proxies.TestOutput result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BarcodeTest_TestOutput.toString());
		if (identifier != null)
			result = barcode.proxies.TestOutput.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BarcodeTest_TestOutput
	 * @param barcodetest_testoutput
	 */
	public final void setBarcodeTest_TestOutput(barcode.proxies.TestOutput barcodetest_testoutput)
	{
		setBarcodeTest_TestOutput(getContext(), barcodetest_testoutput);
	}

	/**
	 * Set value of BarcodeTest_TestOutput
	 * @param context
	 * @param barcodetest_testoutput
	 */
	public final void setBarcodeTest_TestOutput(com.mendix.systemwideinterfaces.core.IContext context, barcode.proxies.TestOutput barcodetest_testoutput)
	{
		if (barcodetest_testoutput == null)
			getMendixObject().setValue(context, MemberNames.BarcodeTest_TestOutput.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BarcodeTest_TestOutput.toString(), barcodetest_testoutput.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return barcodeTestMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final barcode.proxies.BarcodeTest that = (barcode.proxies.BarcodeTest) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Barcode.BarcodeTest";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
